#ifndef ERRORHANDLER
#define ERRORHANDLER

#define ERRORTYPE_NOTEXIST 0x01
#define ERRORTYPE_FILEREADFAILED 0x01 << 1
#define ERRORTYPE_FILEWRITEFAILED 0x01 << 2
#define ERRORTYPE_WRONGNODEDATA 0x01 << 3
#define ERRORTYPE_WRONGELEMENTDATA 0x01 << 4
#define ERRORTYPE_WRONGSCENE 0x01 << 5
#define ERRORTYPE_MEMORYALLOCFAILED 0x01 << 6

class ErrorHandler{
public:
	static void ReportErr(int err);
};

#endif  ERRORHANDLER